# Generated by Django 4.1.7 on 2023-03-05 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choises',
            new_name='Choice',
        ),
    ]
